In [1]:
print("have a nice dayyyy")

have a nice dayyyy


In [9]:
import numpy as np
scores = np.array([[85, 90, 78, 92, 88],  
                    [72, 75, 80, 68, 74],   
                    [95, 88, 92, 96, 90],   
                    [60, 65, 70, 58, 62], 
                    [88, 84, 86, 89, 87]])
print(scores)

[[85 90 78 92 88]
 [72 75 80 68 74]
 [95 88 92 96 90]
 [60 65 70 58 62]
 [88 84 86 89 87]]


In [12]:
#1.Retrieve the scores of Student 3 for all subjects
marks= scores[2]
print(marks)

[95 88 92 96 90]


In [14]:
#2.Retrieve the scores for Subject 2 (column 2) across all students.
sub2= scores[:,1]
print(sub2)

[90 75 88 65 84]


In [17]:
#3.Extract the scores of the first 3 students for the first 2 subjects.Extract the scores of the last 2 students for the last 3 subjects. 
marks=scores[:3 ,:2]
print(marks    )

[[85 90]
 [72 75]
 [95 88]]


In [20]:
#4.Add 5 bonus marks to all scores.
bonus= scores+5
print(bonus)

[[ 90  95  83  97  93]
 [ 77  80  85  73  79]
 [100  93  97 101  95]
 [ 65  70  75  63  67]
 [ 93  89  91  94  92]]


In [23]:
#5.Subtract 10 marks from scores of Subject 4 for all students.
scores[:, 3] -= 10
print(scores)

[[85 90 78 82 88]
 [72 75 80 58 74]
 [95 88 92 86 90]
 [60 65 70 48 62]
 [88 84 86 79 87]]


In [24]:
#6.Calculate the percentage scores of each student assuming each subject is out of 100. 
percentage = np.sum(scores, axis=1) / 5
print(percentage)


[84.6 71.8 90.2 61.  84.8]


In [25]:
# 7.Calculate the average score for each student across all subjects. 
average = np.mean(scores, axis=1)
print(average )


[84.6 71.8 90.2 61.  84.8]


In [29]:
#8.Find the total marks scored by each student. 
total = np.sum(scores, axis =1)
print(total)

[423 359 451 305 424]


In [30]:
#9.Identify the highest score in the entire array. 
highest = np.max(scores)
print(highest)


95


In [31]:
#  10.Determine the average score for each subject
average_scores_subject = np.mean(scores, axis=0)
print(average_scores_subject)


[80.  80.4 81.2 70.6 80.2]


In [32]:
# 11.Find the student with the lowest average score.
lowest_avg_score = np.argmin(np.mean(scores, axis=1))
print(lowest_avg_score)


3
