In [1]:
rollno =101;
name = "rajesh"
print("roll no is:",rollno, end="")
print("name is :",name)

roll no is: 101name is : rajesh


In [14]:
x = ['a', 'x', 'y', 'z', ['d', 'e', 'f'], 'p', 'q', 'r']
x.append('g')
x[4].insert(2, 'h') 

print(x)


['a', 'x', 'y', 'z', ['d', 'e', 'h', 'f'], 'p', 'q', 'r', 'g']


In [17]:
student={'rollno':101,'name':'sahil'}
print(student)
student['fess']=400;
print(student)

{'rollno': 101, 'name': 'sahil'}
{'rollno': 101, 'name': 'sahil', 'fess': 400}


In [19]:
a={2,3,4,5}
a.add(2)
a.add(8)
print(a)

{2, 3, 4, 5, 8}


In [20]:
x=(2,3,4,6)
x=list(x)
x.append(7)
x=tuple(x)
print(x)

(2, 3, 4, 6, 7)


In [22]:
import numpy as np

a = [100,200,300,400,500]

arr = np.array(a)

print(arr)
print(type(arr))

[100 200 300 400 500]
<class 'numpy.ndarray'>


In [1]:
import numpy as np
sales_january = np.array([300, 400])
sales_february = np.array([500, 600])
Answer=np.concatenate((sales_january,sales_february))
print(Answer)

[300 400 500 600]


In [2]:
import numpy as np
data = np.array([1, 2, 3, 4, 5, 6])
Reshap=data.reshape(2,3)
print(Reshap)


[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
scores = np.array([[80, 90], [85, 95]])
reshaped_scores = scores.reshape(-1)
print(reshaped_scores)


[80 90 85 95]
